### PR TITLE
setSharedPreferencesName() in Fragment mode

### PR DESCRIPTION
**Pull request by ruslansennov**

### CODE REVIEW

**Comment by saik0** [comment]
In the demo we allow the Preference framework to handle this for us by setting the title attribute in [pref_headers.xml](https://github.com/saik0/UnifiedPreference/blob/1374d36b418a4dfa6b0059fc1313561d1ff4eb45/demo/res/xml/pref_headers.xml).

What is the use case for having a getter/setter?

**Comment by ruslansennov** [comment]
No, as I know,
this one sets the name of the SharedPreferences file that preferences
managed by this will use.
By default the preferences pairs of (key, value) associates with activity
but not with specified name.

**Comment by saik0** [comment]
Ah, I understand. Why not just do something like this in your activity:

``` java
@Override
public SharedPreferences getSharedPreferences(String name, int mode) {
    return super.getSharedPreferences("foo", mode);
}
```

**Comment by ruslansennov** [comment]
Here is code in my Activity

``` java
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // preferenceManager == null in Fragment Mode, 
    if(getPreferenceManager() != null) {
        getPreferenceManager().setSharedPreferencesName(PREF_FILE_NAME);
    }

    // in Fragment Mode we need call setSharedPreferencesName() 
    // in UnifiedPreference.Fragment.onCreate() method
    //
    // after super.onCreate(savedInstanceState) 
    // (because here preferenceManager is initializing)
    //
    // but before addPreferencesFromResource() and bindPreferenceSummariesToValues()
    // (for correct defaults and selected values visualization)

    ...
}
```

Maybe I wrong?

**Comment by saik0** [comment]
It's not wrong, but the PreferenceManager will eventually call `getSharedPreferences(PREF_FILE_NAME, 0)` from Context instance. Because the Fragment is using the Activity's Context overriding that method instead will get the result of both the Activity and it's Fragments using the same SharedPreference.

In the near future I will be refactoring the code to use a delegation pattern instead of a static utils class. I will include some methods like setSharedPreferencesName() and setSharedPreferencesMode() and delegate to the PreferenceManager like your code does. In the mean time I dont want to add more methods for the user to implement/override.

Closing this pull request for now, but feel free to respond if you have any more questions/comments.

**Comment by saik0** [comment]
UnifiedPreferenceActivity now has setSharedPreferencesName and setSharedPreferencesMode methods that propagate to Fragments. See commit 03e7f9fbbce07656a25045e1fbc0b2e38cf3b424.

**Comment by ruslansennov** [comment]
thank you!

**Comment by saik0** [comment]
Thank you for testing and contributing.

**Pull request closed without merging**
